SELECT Name,FoodType
FROM ANIMAL a INNER JOIN FEEDING f ON a.Species=f.Species

SELECT Class, COUNT(ANIMALID) AS CANT_POR_CLASE
FROM ANIMAL 
GROUP BY Class
ORDER by CANT_POR_CLASE DESC 

SELECT Class, COUNT(ANIMALID) AS ANIMAL_POR_CAT,SUM(FoodPrice) AS INV_ALIM_POR_CLASE
FROM ANIMAL a INNER JOIN FEEDING f ON a.Species=f.Species 
GROUP BY Class 
ORDER BY INV_ALIM_POR_CLASE DESC

SELECT Class, COUNT(ANIMALID) AS ANIMAL_POR_CAT,SUM(FoodPrice) AS INV_ALIM_POR_CLASE
FROM ANIMAL a INNER JOIN FEEDING f ON a.Species=f.Species 
GROUP BY Class 
ORDER BY INV_ALIM_POR_CLASE ASC

SELECT COUNT(DISTINCT FoodType) 
FROM FEEDING
